### PR TITLE
Refactor BuildUtils to work on Run instances.

### PR DESCRIPTION
**Pull request by Vlatombe**
This will help for #60 support of Build Variables for workflow.

### CODE REVIEW

**Comment by aldaris** [comment]
Sigh, I made some comments on the commit, not as part of this PR: https://github.com/Vlatombe/hipchat-plugin/commit/dc9cf6da8803adc6600abf2b8f21174d56e8204b

**Comment by aldaris** [comment]
Could you please also write a new test in BuildUtilsTest for a pure Run scenario? Much appreciated.

**Comment by Vlatombe** [comment]
I've pushed updates to take into account your comments

**Comment by aldaris** [comment]
This change looks excellent now, if it's not much of a hassle, could you please squash the commits?

**Comment by Vlatombe** [comment]
Done

**Comment by aldaris** [comment]
Thank you very much for this contribution.

**Pull request merged**
